-- Init everything
require("plugins")
require("settings")
require("keymappings")
require("autocommands")
require("lualine-config")
require("lsp-config")
require("treesitter-config")
require("mason-config")
require("null-ls-config")
require("cmp-config")
require("Comment-config")
require("nvim-tree-config")
require("nvim-devicons-config")
require("telescope-config")
